// <auto-generated />
namespace Drones.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class relationship_farm_farmer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(relationship_farm_farmer));
        
        string IMigrationMetadata.Id
        {
            get { return "201904201812347_relationship_farm_farmer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
